config/routes.rb
Rails.application.routes.draw do

  root 'trips#index'

  resources :trips do
    resources :infos do
      resources :descriptions
    end
  end

end

app/models/description.rb
class Description < ActiveRecord::Base
  belongs_to :infos
end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :trip, dependent: :destroy
  has_one :description
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :infos

  def name
  end

  def start
  end

  def end
  end

  def self.by_name
    order(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  def index
  end

  def edit
  end

  def new
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :trip
  def index
    @infos = @trip.infos
  end

  def show
  end

  def edit
  end

  def new
    @info = @trip.infos.new
  end

  def create
    @info = @trip.infos.create(info_params)
    redirect_to trip_infos_path(@trip, @info)
  end

  private

  def info_params
    params.require(:info).permit(:places, :comments)
  end

  def trip
    @trip = Trip.find(params[:trip_id])
  end

  def info
    @info = @trip.infos.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.create(trip_params)
    redirect_to trips_path
  end

  def edit
    @trip = Trip.find(trip)
  end

  def update
    trip.update(trip_params)
    redirect_to trips_path
  end

  def destroy
    trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :start, :end)
  end

  def trip
    @trip = Trip.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/descriptions/edit.html.erb
<h1>Descriptions#edit</h1>
<p>Find me in app/views/descriptions/edit.html.erb</p>

app/views/descriptions/index.html.erb
<h1>Descriptions#index</h1>
<p>Find me in app/views/descriptions/index.html.erb</p>

app/views/descriptions/new.html.erb
<h1>Descriptions#new</h1>
<p>Find me in app/views/descriptions/new.html.erb</p>

app/views/infos/_form.html.erb
<%= form_for [@trip, @info] do |f| %>
<%= f.label :places %>
<%= f.text_area :places %>
<br/>
<br/>

<%= f.label :comments %>
<%= f.text_area :comments %>
<br/>
<br/>

<%= f.submit %>
<% end %>

app/views/infos/edit.html.erb
<h1>Infos#edit</h1>
<p>Find me in app/views/infos/edit.html.erb</p>

app/views/infos/index.html.erb
<% if @infos.any? %>
  <% @infos.each do |info| %>
  <%= link_to info.places, trip_info_path(@trip, :id) %>
  <br/>
  <% end %>
<% else %>
  <h1>No Current info</h1>
<% end %>
<%= link_to 'Add More Info', new_trip_info_path(@trip, @info) %>

app/views/infos/new.html.erb
<h1>Trip info for <%= @trip.name %></h1>
<hr/>
<%= render(partial: 'form') %>
<hr/>

app/views/infos/show.html.erb
<h1><%= @info %>hello</h1>
<%= @info.comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VacationTrkr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
<%= f.label :name %>
<%= f.text_area :name %>
   <br/>
   <br/>

<%= f.label :start %>
<%= f.date_select :start%>
  <br/>
  <br/>
<%= f.label :end %>
<%= f.date_select :end%>
  <br/>
  <br/>

<%= f.submit %>
<% end %>
<br/>
<%= link_to 'Cancel', trips_path %>

app/views/trips/edit.html.erb
<h1>Change <%= @trip.name %>'s name</h1>
<%= render(partial: 'form') %>

app/views/trips/index.html.erb
<h1>Trips Tracker</h1>

<%= link_to 'Add Trip', new_trip_path %>
<hr/>

<% if @trips.any? %>
  <% @trips.each do |trip| %>
  <h3><%= trip.name %></h3>
  <%= link_to image_tag("plane.png"), trip_infos_path(trip) %>
  <br/>
  <%= link_to 'Delete', trip_path(trip), method: :delete, data: {confirm: 'Really Delete Trip?'}  %>
  <%= link_to 'Rename', edit_trip_path(trip) %>
  <hr/>
  <% end %>
<% else %>
  <h3>You have no trips, GO TRAVEL BRO</h3>
<% end %>

app/views/trips/new.html.erb
<h1>Create New Trip</h1>

<%= render(partial: 'form') %>